package com.huobi.client.v2.message;


import java.util.List;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

import com.huobi.client.model.Candlestick;
import com.huobi.client.v2.message.entry.CandlestickEntry;

/**
 * The candlestick/kline data received by subscription of candlestick/kline.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class CandlestickMessage {

  /**
   * the symbol you subscribed. like "btcusdt".
   */
  private String symbol;
  /**
   * Get the UNIX formatted timestamp generated by server in UTC.
   */
  private long timestamp;

  /**
   * Get the data of candlestick/kline see {@link Candlestick}
   */
  private List<CandlestickEntry> dataList;
}