package com.huobi.client.v2.message;

import java.util.List;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import com.huobi.client.v2.message.entry.TradeEntry;


/**
 * The trade received by subscription of trade.
 */
@NoArgsConstructor
@AllArgsConstructor
@Data
@Builder
public class TradeMessage {

  /**
   * Get the symbol you subscribed.
   *
   * like "btcusdt".
   */
  private String symbol;

  /**
   * the UNIX formatted timestamp generated by server in UTC.
   */
  private Long timestamp;

  /**
   * the trade.
   *
   * The trade data, see {@link TradeEntry}
   */
  private List<TradeEntry> tradeList;
}