package com.huobi.client.v1.message;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

import com.huobi.client.v1.message.model.TradeSummaryEntry;

/**
 * The summary of trades in last 24 hours
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class TradeSummaryMessage {

  /**
   * the symbol you subscribed.
   *
   * The symbol, like "btcusdt".
   */
  private String symbol;

  /**
   * the UNIX formatted timestamp generated by server in UTC.
   */
  private long timestamp;

  /**
   * the trade summary.
   *
   * The trade summary data, see {@link TradeSummaryEntry}
   */
  private TradeSummaryEntry tradeSummary;

}
