package com.huobi.client.message.model;

import java.math.BigDecimal;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import com.huobi.client.enums.TradeDirection;

/**
 * The trade information with price and amount etc.
 */
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class TradeEntry {

  /**
   * The unique trade id of this trade.
   *
   */
  private String tradeId;

  /**
   * The UNIX formatted timestamp generated by server in UTC.
   */
  private long timestamp;

  /**
   * The trading price in quote currency.
   */
  private BigDecimal price;

  /**
   * The trading volume in base currency.
   */
  private BigDecimal volume;
  /**
   * The direction of the taker trade: 'buy' or 'sell'.
   */
  private TradeDirection direction;

}
