package com.huobi.client.v1.message.model;

import java.math.BigDecimal;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@ToString
public class TradeSummaryEntry {

  /**
   * The symbol you subscribed.
   *
   * like "btcusdt".
   */
  private String symbol;

  /**
   * The UNIX formatted timestamp generated by server in UTC.
   */
  private Long timestamp;

  /**
   * The turnover of last 24 hours
   */
  private BigDecimal turnover;

  /**
   * The volume of last 24 hours
   */
  private BigDecimal volume;

  /**
   * The first price in last 24 hours
   */
  private BigDecimal open;

  /**
   * The last price in last 24 hours
   */
  private BigDecimal close;

  /**
   * The highest price in last 24 hours
   */
  private BigDecimal high;

  /**
   * The lowest price in last 24 hours
   */
  private BigDecimal low;

  /**
   * The number of trades in last 24 hours
   */
  private Integer numOfTrades;

}
