package com.huobi.client.event;

import java.util.LinkedList;
import java.util.List;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import com.huobi.client.model.AccountChange;
import com.huobi.client.enums.AccountChangeType;

/**
 * The account change information received by subscription of account.
 */
@NoArgsConstructor
@AllArgsConstructor
@Data
@Builder
public class AccountEvent {

  /**
   * the UNIX formatted timestamp generated by server in UTC.
   */
  private long timestamp = 0;

  /**
   * The event that asset change notification related.
   *
   * The change type, see {@link AccountChangeType}
   */
  private AccountChangeType changeType = AccountChangeType.INVALID;

  /**
   * the detail of account change.
   *
   * The list of account change, see {@link AccountChange}
   */
  private List<AccountChange> accountChangeList = new LinkedList<>();
}
