package com.huobi.client.message;

import java.util.List;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

import com.huobi.client.message.model.CandlestickEntry;
import com.huobi.client.model.Candlestick;
import com.huobi.gateway.enums.CandlestickIntervalEnum;

/**
 * The candlestick/kline data received by subscription of candlestick/kline.
 */
@NoArgsConstructor
@AllArgsConstructor
@Data
@Builder
@ToString
public class CandlestickMessage {

  /**
   * the symbol you subscribed. like "btcusdt".
   */
  private String symbol;
  /**
   * Get the UNIX formatted timestamp generated by server in UTC.
   */
  private long timestamp;
  /**
   * Get candlestick/kline interval you subscribed. see {@link CandlestickIntervalEnum}
   */
  private CandlestickIntervalEnum interval;

  /**
   * Get the data of candlestick/kline see {@link Candlestick}
   */
  private List<CandlestickEntry> dataList;
}

