package com.huobi.client.message;

import java.util.List;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import com.huobi.client.message.model.PriceLevelEntry;
import com.huobi.client.model.DepthEntry;

/**
 * The price depth received by subscription of price depth.
 */
@NoArgsConstructor
@AllArgsConstructor
@Data
@Builder
public class PriceDepthMessage {

  /**
   * Get the symbol you subscribed.
   *
   * like "btcusdt".
   */
  private String symbol;

  /**
   * the UNIX formatted timestamp generated by server in UTC.
   */
  private Long timestamp;

  /**
   * the list of the bid depth.
   *
   * The price depth list, see {@link DepthEntry}
   */
  private List<PriceLevelEntry> bids;

  /**
   * the list of the ask depth.
   *
   * The price depth list, see {@link DepthEntry}
   */
  private List<PriceLevelEntry> asks;
}
