package com.huobi.client.message;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import com.huobi.client.model.TradeStatistics;

/**
 * The 24H trade statistics received by subscription of trade statistics.
 */
@NoArgsConstructor
@AllArgsConstructor
@Data
@Builder
public class TradeStatisticsMessage {

  /**
   * the symbol you subscribed.
   *
   * The symbol, like "btcusdt".
   */
  private String symbol;

  /**
   * the UNIX formatted timestamp generated by server in UTC.
   */
  private long timeStamp;

  /**
   * the trade statistics.
   *
   * The trade statistics data, see {@link TradeStatistics}
   */
  private TradeStatistics tradeStatistics;
}
