package com.huobi.client.v1.event;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import com.huobi.client.v1.model.Order;

/**
 * The order update received by subscription of order update.
 */
@NoArgsConstructor
@AllArgsConstructor
@Data
@Builder
public class OrderUpdateEvent {

  /**
   * the symbol you subscribed. like "btcusdt".
   */
  private String symbol;

  /**
   * the UNIX formatted timestamp generated by server in UTC.
   */
  private long timestamp;

  /**
   * the order detail.
   *
   * The order data, see {@link Order}
   */
  private Order data = null;
}
