package com.huobi.client.v1.event;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import com.huobi.client.v1.model.PriceDepth;

/**
 * The price depth received by subscription of price depth.
 */
@NoArgsConstructor
@AllArgsConstructor
@Data
@Builder
public class PriceDepthEvent {

  /**
   * Get the symbol you subscribed.
   *
   * like "btcusdt".
   */
  private String symbol;

  /**
   * the UNIX formatted timestamp generated by server in UTC.
   */
  private Long timestamp;

  /**
   * the price depth.
   *
   * The price depth data, see {@link PriceDepth}
   */
  private PriceDepth data;
}
